# Generated by Django 4.2.1 on 2023-05-31 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=56.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='text',
            field=models.TextField(default='aaaaaaaaaaa ssssssssssssssssss'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('text', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.course')),
            ],
        ),
    ]
