# Generated by Django 4.2.1 on 2023-05-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_duration_course_language_course_text_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='source',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
